name: oneshelf

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "5173:5173"
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "[::1]:8090:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpass
      # Creates default database with single superuser
      # Essentially equivalent to the following SQL statements on initialization
      #
      # CREATE DATABASE oneshelf;
      # CREATE USER oneshelf WITH PASSWORD "$PGPASS";
      # GRANT ALL PRIVILEGES ON DATABASE oneshelf TO oneshelf;
      POSTGRES_USER: oneshelf
      POSTGRES_DB: oneshelf
    volumes:
      - type: bind
        source: ./init-scripts/
        # Contains sql, sql.gz, or sh files
        # Executed in sorted locale order (en_US.utf8 by default)
        target: /docker-entrypoint-initdb.d/
        read_only: true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "oneshelf"]
      interval: 10s
      start_period: 30s
    secrets:
      - pgpass

volumes:
  frontend-node-modules:

secrets:
  pgpass:
    # File must exist in order for postgres to start
    file: .pgpass
